### PR TITLE
Modified ignore_configcheck behavior

### PR DESCRIPTION
**Pull request by n0trax**
Ignore all control_binary errors if ignore_checkconfig flag is True.

### CODE REVIEW

**Comment by robinro** [comment]
This ignores any error including "module does not exist" if I understand it correctly. 
Should we just call it `ignore_warnings` then?

**Comment by n0trax** [comment]
Yes, that's correct.
I think `ignore_warnings` is much better.

**Comment by n0trax** [comment]
What do you think of `ignore_configcheck_errors`? Because we are only ignoring the errors of the apache2ctl -M result.

**Comment by robinro** [comment]
Thats getting to long...
I'd rather stick with `ignore_configcheck` then.

**Pull request closed without merging**
